### ISSUE TITLE
Adding proper page title and social share card

### ISSUE THREAD

**Issue by devinhalladay** [rms-open-letter/rms-open-letter.github.io#1395] opened 2021-03-24 18:15 UTC
Thanks for taking this initiative.

I'm wondering if the community would be supportive of adding a proper page title to this site, and possibly an image for share cards on social media, to increase visibility and accessibility on social media?

If so, I'm happy to submit a PR for the image, or collaborate with others to provide design guidance.

**Comment by ehashman** [comment] 2021-03-24 18:20
Feel free to submit a PR!

Keep in mind the following things:
- Adding an image impacts page load times (size) and would need to be described for accessibility (screen readers)
- Adding social media share links should not come with analytics trackers if possible. We don't want to load external JS because it will impact page load times/accessibility.

If you can address both of those things (i.e. URL-only shares with very small embedded images or existing unicode) I think it would be fine :)

**Comment by devinhalladay** [comment] 2021-03-24 18:24
Thank you @ehashman! These are great points. To be clear, my intention is to simply add page metadata to enrich display of the page on social media. I am happy to also consider ways of adding non-tracker social share links to the site as well — not a bad idea at all.

I'll work on a PR when I get a chance after work. If someone beats me to it, more power to you!

**Comment by ehashman** [comment] 2021-03-24 19:25
Ahh, so like OpenGraph metadata? I have no idea how that works with GitHub pages so thanks for volunteering to take a look :)

**Comment by devinhalladay** [comment] 2021-03-24 22:34
Okay, I have not had time to explore non-tracking social share links, but I have put up a PR with some suggested metadata information as well as a share card image, which is open source and [available to anyone to edit here on Figma](https://www.figma.com/file/AvIRMUJEju3NZycmbDYe6L/Stallman-Petition-OpenGraph-Image?node-id=0%3A1).

**Comment by devinhalladay** [comment] 2021-03-24 22:43
If that PR is able to be merged, let's leave this issue open for a bit longer while I explore non-tracking share links. If those are not strictly possible, I will close the issue without addressing share links.

**Comment by ehashman** [comment] 2021-03-25 01:45
Confirmed that the new OG metadata is working on Twitter :+1: :bird:

**Comment by ziggythehamster** [comment] 2021-03-25 02:00
This is poorly documented by Facebook, but you need only `<a target="_blank">` for a FB share link; no JavaScript.

However, you do need to have a Facebook application registered (with no permissions at all requested). Here's the URL format to shove into href:

```
https://www.facebook.com/dialog/share?app_id=X&display=popup&href=https://whatever-but-urlencoded
```

You can also add a `&redirect_uri=`. You would want to do that to ensure that the window closes. Point it at a file called `close_window.html` on the same origin as the page with the `<a>` and give it this content:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Close Me</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <script type="text/javascript">
    window.close();
  </script>
</head>

<body>
</body>
</html>
```

No JavaScript? Works the same as without the redirect_uri.

Currently checking to see if I have a Twitter equivalent.

**Comment by cassidyjames** [comment] 2021-03-25 02:04
Twitter equivalent is:

```
https://twitter.com/intent/tweet?text=ESCAPED%20TEXT%20HERE&url=URL HERE
```

**Comment by ziggythehamster** [comment] 2021-03-25 02:04
Lovely, I have both Twitter and LinkedIn.

Twitter:

```
https://twitter.com/intent/tweet?url=https://whatever-but-urlencoded&text=the%20tweet%20body
```

(text is optional)

LinkedIn:

```
https://www.linkedin.com/shareArticle?url=https://whatever-but-urlencoded&title=Title%20goes%20here&summary=Summary%20is%20longer%20but%20goes%20here
```

With LinkedIn, the first time it pulls the metadata, it's stuck there for a week. You have to go to the [Post Inspector](https://www.linkedin.com/post-inspector/) to fix it.

**Comment by cassidyjames** [comment] 2021-03-25 02:05
Reddit:

```
http://www.reddit.com/submit?title=ESCAPED%20TEXT&url=URL
```

**Comment by ziggythehamster** [comment] 2021-03-25 02:06
Looks like we replied at the same time, lol :).

**Comment by devinhalladay** [comment] 2021-03-25 02:16
thanks everyone! I will add these share links now. you rock.

**Comment by devinhalladay** [comment] 2021-03-25 16:58
Edit: #1968 was reverted due to its accidental removal of i18n page links in the navigation header.

New PR at #1984

**Comment by ehashman** [comment] 2021-03-25 17:54
I think we can close this now!

**Closed by ehashman** 2021-03-25 17:54 UTC

**Comment by devinhalladay** [comment] 2021-03-25 17:56
Yes, we are all good! Thank you @ehashman and others above for collaborating with me on the OpenGraph card and share links. It's so cool to see this being shared all over social media with a nice image attached. Very powerful stuff.

Keep going, you all are doing amazing work.
