### ISSUE TITLE
Footnote 9 currently unclickable

### ISSUE THREAD

**Issue by ell1e** [rms-open-letter/rms-open-letter.github.io#1235] opened 2021-03-24 16:06 UTC
It appears to be as of now (the point in time I made this ticket) footnote 9 is not a clickable link in the Appendix, while I assume it is meant to be: https://rms-open-letter.github.io/appendix

> “there is little evidence to justify the widespread assumption that willing participation in pedophilia hurts children.”[9]

^ this `[9]`

**Comment by ehashman** [comment] 2021-03-24 16:12
It's clickable in the GitHub render but not on the site. Looking into it.

**Comment by appetrosyan** [comment] 2021-03-24 16:29
Since this would be changing the underlying contents of the page in some form or another, and retractions of factually wrong corrections were closed because the text is "frozen", it would be highly hypocritical of @neilmcgovern not to close this issue and to make the change.

**Comment by KaiTheCEO** [comment] 2021-03-25 02:31
I am able to click on it so it might be fixed.

**Comment by ehashman** [comment] 2021-03-25 02:33
Confirmed.

**Closed by ehashman** 2021-03-25 02:33 UTC
